wandb_version: 1

learning_rate:
  desc: null
  value: 0.001
epochs:
  desc: null
  value: 25
max_size:
  desc: null
  value: null
subset:
  desc: null
  value: true
subset_size:
  desc: null
  value: 0.5
batchsize:
  desc: null
  value: 40
use_embeddings:
  desc: null
  value: true
embedding_name:
  desc: null
  value: esm2_t36_3B
mean_embedding:
  desc: null
  value: false
embedding_dim:
  desc: null
  value: 2560
dataset:
  desc: null
  value: gold_stand
model:
  desc: null
  value: dscript_like
_wandb:
  desc: null
  value:
    python_version: 3.8.18
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1700571144.096347
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 23
      4: 3.8.18
      5: 0.15.12
      8:
      - 5
      13: linux-x86_64
